version: "3.8"
services:
  flask-app:
    #image: flask_img
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "flask-app"
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017/
    networks:
      - flask-webapp-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - flask-webapp-network
networks:
  flask-webapp-network:
    driver: bridge